package com.happyelements.store.tikv;

import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;

/**
 * JNA Wrapper for library <b>libmath</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface LibmathLibrary extends Library {
    public static final String JNA_LIBRARY_NAME = "tikv-client";
    public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(LibmathLibrary.JNA_LIBRARY_NAME);
    public static final LibmathLibrary INSTANCE = (LibmathLibrary) Native.loadLibrary(LibmathLibrary.JNA_LIBRARY_NAME, LibmathLibrary.class);

    GoSlice.ByValue echo(GoSlice.ByValue msg);
    void test();
}

